version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: imagine
      POSTGRES_PASSWORD: imagine@password.root
      POSTGRES_DB: imagine
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - postgres
    links:
      - postgres